name: Deploy Static Flask App

on:
  push:
    branches:
      - main
    paths:
      - app.py
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Gitleaks scan
        shell: bash
        run: |
          set -e
          ARCH=$(uname -m)
          if [ "$ARCH" = "x86_64" ]; then
            FILE="gitleaks-linux-amd64"
          elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
            FILE="gitleaks-linux-arm64"
          else
            FILE="gitleaks-linux-amd64"
          fi
          echo "Downloading gitleaks binary..."
          curl -sSfL "https://github.com/zricethezav/gitleaks/releases/latest/download/${FILE}" -o gitleaks
          chmod +x gitleaks
          ./gitleaks --version
          ./gitleaks detect --source . --no-progress

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify data.json exists
        run: |
          if [ ! -f data.json ]; then
            echo "data.json not found in repo root"
            exit 1
          fi

      - name: Export static site
        run: |
          python app.py --export

      - name: Upload output artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: output

  deploy:
    name: Deploy to GitHub Pages
    needs: [build]
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish-dir: ./output